_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 51
                - 53
                - 55
                - 63
            "2":
                - 1
                - 5
                - 41
                - 49
                - 51
                - 53
                - 55
                - 63
            "3":
                - 2
                - 13
                - 14
                - 15
                - 16
                - 23
                - 55
                - 61
            "4": 3.9.20
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size:
    value: 1
blr:
    value: 0.004
dataset_csv:
    value: dataset_csv/biomarker/BCNB_ERPRHER2.csv
device:
    value: cuda
drop_path_rate:
    value: 0
dropout:
    value: 0.1
epochs:
    value: 30
exp_code:
    value: eval_pretrained_BCNB_ERPRHER2
exp_name:
    value: ""
experiment:
    value: finetune
feat_layer:
    value: "11"
folds:
    value: 5
fp16:
    value: true
freeze:
    value: false
gc:
    value: 32
global_pool:
    value: false
input_dim:
    value: 768
latent_dim:
    value: 768
layer_decay:
    value: 0.95
lr:
    value: 0.0001
lr_scheduler:
    value: cosine
max_wsi_size:
    value: 250000
mil_model_size:
    value: small
mil_type:
    value: clam_sb
min_lr:
    value: 1e-06
model_arch:
    value: vit_base
model_code:
    value: eval_pretrained
model_select:
    value: val
n_classes:
    value: 3
num_workers:
    value: 10
optim:
    value: adamw
optim_wd:
    value: 0.05
pat_strat:
    value: false
pool_method:
    value: cls_token
pre_split_dir:
    value: ""
pretrain_model:
    value: CONCH
pretrain_model_type:
    value: patch_level
pretrained:
    value: /ruiyan/yuhao/project/FMBC/ibot/checkpoint0040.pth
report_to:
    value: wandb
return_all_tokens:
    value: true
root_path:
    value: /ruiyan/yuhao/tile_embed/BCNB/CONCH
save_dir:
    value: outputs/BCNB_ERPRHER2/CONCH
seed:
    value: 0
split_dir:
    value: data_split/BCNB_ERPRHER2
split_key:
    value: slide_id
task:
    value: BCNB_ERPRHER2
task_cfg_path:
    value: task_configs/BCNB_ERPRHER2.yaml
task_code:
    value: BCNB_ERPRHER2
task_config:
    value:
        label_dict:
            ER: 0
            HER2: 2
            PR: 1
        max_tiles: 6000
        name: BCNB_ERPRHER2
        setting: multi_label
        shuffle_tiles: true
tile_size:
    value: 256
tuning_method:
    value: null
val_r:
    value: 0
warmup_epochs:
    value: 0
weighted_sample:
    value: false
