dino:
  head_n_prototypes: 131072
  head_bottleneck_dim: 384
ibot:
  separate_head: true
  head_n_prototypes: 131072
train:
  batch_size_per_gpu: 140
  dataset_path: ImageNet:split=TRAIN
  centering: sinkhorn_knopp
  num_workers: 16
student:
  arch: vit_h
  patch_size: 14
  drop_path_rate: 0.4
  ffn_layer: SwiGLUPacked
  block_chunks: 4
  num_register_tokens: 8
  layerscale: 1e-5
teacher:
  momentum_teacher: 0.994
optim:
  epochs: 4000
  weight_decay_end: 0.2
  base_lr: 2.0e-04  # learning rate for a batch size of 1024
  warmup_epochs: 80
  layerwise_decay: 1.0
crops:
  local_crops_size: 98