_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 51
                - 53
                - 55
                - 63
            "2":
                - 1
                - 5
                - 41
                - 49
                - 51
                - 53
                - 55
                - 63
            "3":
                - 2
                - 13
                - 14
                - 15
                - 16
                - 23
                - 55
                - 61
            "4": 3.9.20
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size:
    value: 1
blr:
    value: 0.002
dataset_csv:
    value: dataset_csv/subtype/BRACS_fine.csv
device:
    value: cuda
drop_path_rate:
    value: 0
dropout:
    value: 0.1
epochs:
    value: 30
exp_code:
    value: eval_pretrained_BRACS_Fine
exp_name:
    value: ""
experiment:
    value: finetune
feat_layer:
    value: "11"
folds:
    value: 5
fp16:
    value: true
freeze:
    value: false
gc:
    value: 32
global_pool:
    value: false
input_dim:
    value: 768
latent_dim:
    value: 768
layer_decay:
    value: 0.95
lr:
    value: 0.0001
lr_scheduler:
    value: cosine
max_wsi_size:
    value: 250000
min_lr:
    value: 1e-06
model_arch:
    value: vit_base
model_code:
    value: eval_pretrained
model_select:
    value: last_epoch
n_classes:
    value: 7
num_workers:
    value: 10
optim:
    value: adamw
optim_wd:
    value: 0.05
pat_strat:
    value: false
pre_split_dir:
    value: ""
pretrained:
    value: /ruiyan/yuhao/project/FMBC/ibot/checkpoint.pth
report_to:
    value: wandb
root_path:
    value: /ruiyan/yuhao/embedding/BRACS
save_dir:
    value: outputs/BRACS_fine/BRACS_Fine/eval_pretrained_BRACS_Fine
seed:
    value: 0
split_dir:
    value: BRACS_Fine
split_key:
    value: slide_id
task:
    value: BRACS_Fine
task_cfg_path:
    value: task_configs/bracs_fine.yaml
task_code:
    value: BRACS_Fine
task_config:
    value:
        add_metrics:
            - qwk
        label_dict:
            "0": 0
            "1": 1
            "2": 2
            "3": 3
            "4": 4
            "5": 5
            "6": 6
        max_tiles: 3000
        name: BRACS_Fine
        setting: multi_class
        shuffle_tiles: true
tile_size:
    value: 256
val_r:
    value: 0
warmup_epochs:
    value: 0
weighted_sample:
    value: false
