# this corresponds to the default config
train:
  dataset_path: ImageNet:split=TRAIN
  batch_size_per_gpu: 450
  saveckp_freq: 500
  OFFICIAL_EPOCH_LENGTH: 1000
student:
  block_chunks: 4
  arch: vit_base
dino:
  head_n_prototypes: 384
ibot:
  head_n_prototypes: 384
optim:
  epochs: 10
evaluation:
  lr: 0.001
  eval_period_iterations: 1000

  
  