_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 51
                - 53
                - 55
                - 63
            "2":
                - 1
                - 5
                - 41
                - 49
                - 51
                - 53
                - 55
                - 63
            "3":
                - 2
                - 13
                - 14
                - 15
                - 16
                - 23
                - 55
                - 61
            "4": 3.10.16
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: 1
blr:
    value: 0.004
dataset_csv:
    value: dataset_csv/subtype/AIDPATH_GRADE.csv
device:
    value: cuda
drop_path_rate:
    value: 0
dropout:
    value: 0.1
epochs:
    value: 25
exp_code:
    value: eval_pretrained_AIDPATH_GRADE
exp_name:
    value: ""
experiment:
    value: finetune
feat_layer:
    value: "11"
folds:
    value: 5
fp16:
    value: true
freeze:
    value: false
gc:
    value: 32
global_pool:
    value: false
input_dim:
    value: 768
latent_dim:
    value: 768
layer_decay:
    value: 0.95
lr:
    value: 0.0001
lr_scheduler:
    value: cosine
max_wsi_size:
    value: 250000
mil_model_size:
    value: small
mil_type:
    value: clam_sb
min_lr:
    value: 1e-06
model_arch:
    value: vit_base
model_code:
    value: eval_pretrained
model_select:
    value: val
n_classes:
    value: 2
num_workers:
    value: 10
optim:
    value: adamw
optim_wd:
    value: 0.05
pat_strat:
    value: false
pool_method:
    value: cls_token
pre_split_dir:
    value: ""
pretrain_model:
    value: TITAN
pretrain_model_type:
    value: slide_level
pretrained:
    value: /ruiyan/yuhao/project/FMBC/ibot/checkpoint0040.pth
report_to:
    value: wandb
return_all_tokens:
    value: true
root_path:
    value: /data4/embedding/AIDPATH/TITAN
save_dir:
    value: outputs/AIDPATH_GRADE/TITAN/LR
seed:
    value: 0
split_dir:
    value: data_split/AIDPATH_GRADE
split_key:
    value: slide_id
task:
    value: AIDPATH_GRADE
task_cfg_path:
    value: task_configs/AIDPATH_GRADE.yaml
task_code:
    value: AIDPATH_GRADE
task_config:
    value:
        add_metrics:
            - qwk
        label_dict:
            "2": 0
            "3": 1
        max_tiles: 4000
        name: AIDPATH_GRADE
        setting: multi_class
        shuffle_tiles: true
tile_size:
    value: 256
tuning_method:
    value: LR
val_r:
    value: 0
warmup_epochs:
    value: 0
weighted_sample:
    value: false
