_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 51
                - 53
                - 55
                - 63
            "2":
                - 1
                - 5
                - 41
                - 49
                - 51
                - 53
                - 55
                - 63
            "3":
                - 13
                - 14
                - 15
                - 16
                - 23
                - 55
            "4": 3.9.20
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size:
    value: 1
blr:
    value: 0.004
dataset_csv:
    value: dataset_csv/biomarker/IMPRESS_HER2_2subtype.csv
device:
    value: cuda
drop_path_rate:
    value: 0
dropout:
    value: 0.1
epochs:
    value: 30
exp_code:
    value: eval_pretrained_IMPRESS_HER2_2subtype
exp_name:
    value: ""
experiment:
    value: finetune
feat_layer:
    value: "11"
folds:
    value: 5
fp16:
    value: true
freeze:
    value: false
gc:
    value: 32
global_pool:
    value: false
input_dim:
    value: 768
latent_dim:
    value: 768
layer_decay:
    value: 0.95
lr:
    value: 0.0001
lr_scheduler:
    value: cosine
max_wsi_size:
    value: 250000
mil_model_size:
    value: small
mil_type:
    value: clam_sb
min_lr:
    value: 1e-06
model_arch:
    value: vit_base
model_code:
    value: eval_pretrained
model_select:
    value: val
n_classes:
    value: 9
num_workers:
    value: 10
optim:
    value: adamw
optim_wd:
    value: 0.05
pat_strat:
    value: false
pool_method:
    value: cls_token
pre_split_dir:
    value: ""
pretrain_model:
    value: TITAN
pretrain_model_type:
    value: slide_level
pretrained:
    value: /ruiyan/yuhao/project/FMBC/ibot/checkpoint0040.pth
report_to:
    value: wandb
return_all_tokens:
    value: true
root_path:
    value: /ruiyan/yuhao/tile_embed/IMPRESS/TITAN
save_dir:
    value: outputs/IMPRESS_HER2_2subtype/TITAN
seed:
    value: 0
split_dir:
    value: data_split/IMPRESS_HER2_2subtype
split_key:
    value: slide_id
task:
    value: IMPRESS_HER2_2subtype
task_cfg_path:
    value: task_configs/IMPRESS_HER2_2subtype.yaml
task_code:
    value: IMPRESS_HER2_2subtype
task_config:
    value:
        label_dict:
            CD8-intratumoral (cutoff 10%, 1- positive, 0-negative): 6
            CD8-peritumoral  (cutoff 10%, 1- positive, 0-negative): 5
            CD163-intratumoral  (cutoff 10%, 1- positive, 0-negative): 7
            CD163-peritumoral (cutoff 10%, 1- positive, 0-negative): 8
            ER (+-1/-0): 0
            PD-L1-stroma  (cutoff 1%, 1- positive, 0-negative): 4
            PD-L1-tumor (cutoff 1%, 1- positive, 0-negative): 3
            PR (+/-): 1
            pCR: 2
        max_tiles: 4000
        name: IMPRESS_HER2_2subtype
        setting: multi_label
        shuffle_tiles: true
tile_size:
    value: 256
tuning_method:
    value: null
val_r:
    value: 0
warmup_epochs:
    value: 0
weighted_sample:
    value: false
