_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 51
                - 53
                - 55
                - 63
            "2":
                - 1
                - 5
                - 41
                - 49
                - 51
                - 53
                - 55
                - 63
            "3":
                - 13
                - 14
                - 15
                - 16
                - 23
                - 55
            "4": 3.9.20
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size:
    value: 1
blr:
    value: 0.004
dataset_csv:
    value: dataset_csv/expression_prediction/TCGA-Genexp.csv
device:
    value: cuda
drop_path_rate:
    value: 0
dropout:
    value: 0.1
epochs:
    value: 30
exp_code:
    value: eval_pretrained_TCGA-BRCA-Gene-Exp
exp_name:
    value: ""
experiment:
    value: finetune
feat_layer:
    value: "11"
folds:
    value: 5
fp16:
    value: true
freeze:
    value: false
gc:
    value: 32
global_pool:
    value: false
input_dim:
    value: 1536
latent_dim:
    value: 768
layer_decay:
    value: 0.95
lr:
    value: 0.0001
lr_scheduler:
    value: cosine
max_wsi_size:
    value: 250000
mil_model_size:
    value: small
mil_type:
    value: clam_sb
min_lr:
    value: 1e-06
model_arch:
    value: vit_base
model_code:
    value: eval_pretrained
model_select:
    value: val
n_classes:
    value: 50
num_workers:
    value: 10
optim:
    value: adamw
optim_wd:
    value: 0.05
pat_strat:
    value: false
pre_split_dir:
    value: ""
pretrain_model:
    value: Gigapath_tile
pretrain_model_type:
    value: patch_level
pretrained:
    value: /ruiyan/yuhao/project/FMBC/ibot/checkpoint.pth
report_to:
    value: wandb
root_path:
    value: /ruiyan/yuhao/tile_embed/TCGA-BRCA
save_dir:
    value: outputs/TCGA-BRCA-Gene-Exp/Gigapath_tile
seed:
    value: 0
split_dir:
    value: data_split/TCGA-BRCA-Gene-Exp
split_key:
    value: slide_id
task:
    value: TCGA-BRCA-Gene-Exp
task_cfg_path:
    value: task_configs/TCGA-BRCA-Gene-Exp.yaml
task_code:
    value: TCGA-BRCA-Gene-Exp
task_config:
    value:
        add_metrics:
            - qwk
        label_dict:
            ACTR3B: 25
            ANLN: 26
            BAG1: 27
            BCL2: 19
            BIRC5: 28
            BLVRA: 29
            CCNB1: 20
            CCNE1: 10
            CDC6: 30
            CDC20: 21
            CDH3: 31
            CENPF: 11
            CEP55: 12
            CXXC5: 32
            EGFR: 33
            ERBB2: 18
            ESR1: 9
            EXO1: 34
            FGFR4: 13
            FOXA1: 35
            FOXC1: 36
            GPR160: 37
            GRB7: 38
            KIF2C: 8
            KRT5: 39
            KRT14: 7
            KRT17: 6
            MAPT: 5
            MDM2: 40
            MELK: 41
            MIA: 4
            MKI67: 3
            MLPH: 42
            MMP11: 14
            MYBL2: 43
            MYC: 44
            NAT1: 22
            NDC80: 49
            NUF2: 47
            ORC6: 48
            PGR: 2
            PHGDH: 45
            PTTG1: 1
            RRM2: 23
            SFRP1: 15
            SLC39A6: 46
            TMEM45B: 16
            TYMS: 17
            UBE2C: 24
            UBE2T: 0
        max_tiles: 4000
        name: TCGA-BRCA-Gene-Exp
        setting: regression
        shuffle_tiles: true
tile_size:
    value: 256
val_r:
    value: 0
warmup_epochs:
    value: 0
weighted_sample:
    value: false
